# Joseph S. Wirth, 2024
## provides a conda environment for running the python scripts found in this folder
## commands:
##        $ conda env create -f environment.yml
##        $ conda activate misc-python

name: misc-python
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython >=1.81
  - pip >=24.0
  - python >=3.9, <3.12
  - r-base >=4.3
  - sra-tools
  - pip:
      - rpy2
      - khmer
